on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
